### ISSUE TITLE
The latest `newrelic-lambda-layers-python` image returns `xxx is not JSON serializable`

### ISSUE THREAD

**Issue by kv5h** [newrelic/newrelic-lambda-layers#292]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

The latest Docker layer image released with [`v10.3.0.0_python`](https://github.com/newrelic/newrelic-lambda-layers/releases/tag/v10.3.0.0_python) returns an error which has not appeared in the previous version.

The error is as following:

```json
{
  "errorMessage": "<module 'aws_xray_sdk.version' from '/var/lang/lib/python3.9/site-packages/aws_xray_sdk/version.py'> is not JSON serializable",
  "errorType": "TypeError",
  "requestId": "7f67dec2-e876-4429-9eec-728165bc18ba",
  "stackTrace": [
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/packages/wrapt/wrappers.py\", line 598, in __call__\n    return self._self_wrapper(self.__wrapped__, self._self_instance,\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic_lambda/lambda_handler.py\", line 266, in _nr_lambda_handler_wrapper_\n    return result\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/api/transaction.py\", line 660, in __exit__\n    self._application.record_transaction(node)\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/api/application.py\", line 161, in record_transaction\n    self._agent.record_transaction(self._name, data)\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/core/agent.py\", line 586, in record_transaction\n    application.harvest(flexible=False)\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/core/application.py\", line 1273, in harvest\n    self._active_session.send_loaded_modules(self.modules)\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/core/data_collector.py\", line 267, in send_loaded_modules\n    return self._protocol.send(\"update_loaded_modules\", payload)\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/core/agent_protocol.py\", line 229, in send\n    params, headers, payload = self._to_http(method, payload)\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/core/agent_protocol.py\", line 274, in _to_http\n    return params, self._headers, json_encode(payload).encode(\"utf-8\")\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/common/encoding_utils.py\", line 91, in json_encode\n    return json.dumps(obj, **_kwargs)\n",
    "  File \"/var/lang/lib/python3.9/json/__init__.py\", line 234, in dumps\n    return cls(\n",
    "  File \"/var/lang/lib/python3.9/json/encoder.py\", line 199, in encode\n    chunks = self.iterencode(o, _one_shot=True)\n",
    "  File \"/var/lang/lib/python3.9/json/encoder.py\", line 257, in iterencode\n    return _iterencode(o, 0)\n",
    "  File \"/opt/python/lib/python3.9/site-packages/newrelic/common/encoding_utils.py\", line 78, in _encode\n    raise TypeError(repr(o) + \" is not JSON serializable\")\n"
  ]
}
```
       

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce

Using Dockerfile:

```dockerfile
# The previous version returns no error
#FROM public.ecr.aws/newrelic-lambda-layers-for-docker/newrelic-lambda-layers-python:39@sha256:8703f4261781b1ba4d3f66a34e922a3bd83ea08a2ec6966750f28829068689bd AS layer

# The latest one returns an error
FROM public.ecr.aws/newrelic-lambda-layers-for-docker/newrelic-lambda-layers-python:39 AS layer

FROM public.ecr.aws/lambda/python:3.9
COPY --from=layer /opt/ /opt/

# The other configurations here...

CMD [ "newrelic_lambda_wrapper.handler" ]
```

And then, call local Lambda container with `curl -s "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{}' | jq .`.

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour

The command returns no error.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

The Lambda container log says:

```
[ERROR] TypeError: <module 'aws_xray_sdk.version' from '/var/lang/lib/python3.9/site-packages/aws_xray_sdk/version.py'> is not JSON serializable
Traceback (most recent call last):
  File "/opt/python/lib/python3.9/site-packages/newrelic/packages/wrapt/wrappers.py", line 598, in __call__
    return self._self_wrapper(self.__wrapped__, self._self_instance,
  File "/opt/python/lib/python3.9/site-packages/newrelic_lambda/lambda_handler.py", line 266, in _nr_lambda_handler_wrapper_
    return result
  File "/opt/python/lib/python3.9/site-packages/newrelic/api/transaction.py", line 660, in __exit__
    self._application.record_transaction(node)
  File "/opt/python/lib/python3.9/site-packages/newrelic/api/application.py", line 161, in record_transaction
    self._agent.record_transaction(self._name, data)
  File "/opt/python/lib/python3.9/site-packages/newrelic/core/agent.py", line 586, in record_transaction
    application.harvest(flexible=False)
  File "/opt/python/lib/python3.9/site-packages/newrelic/core/application.py", line 1273, in harvest
    self._active_session.send_loaded_modules(self.modules)
  File "/opt/python/lib/python3.9/site-packages/newrelic/core/data_collector.py", line 267, in send_loaded_modules
    return self._protocol.send("update_loaded_modules", payload)
  File "/opt/python/lib/python3.9/site-packages/newrelic/core/agent_protocol.py", line 229, in send
    params, headers, payload = self._to_http(method, payload)
  File "/opt/python/lib/python3.9/site-packages/newrelic/core/agent_protocol.py", line 274, in _to_http
    return params, self._headers, json_encode(payload).encode("utf-8")
  File "/opt/python/lib/python3.9/site-packages/newrelic/common/encoding_utils.py", line 91, in json_encode
    return json.dumps(obj, **_kwargs)
  File "/var/lang/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/var/lang/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/var/lang/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/python/lib/python3.9/site-packages/newrelic/common/encoding_utils.py", line 78, in _encode
    raise TypeError(repr(o) + " is not JSON serializable")
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

```
>>> docker version
Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:38:18 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.35.1 (173168)
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:19 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.7.21
  GitCommit:        472731909fa34bd7bc9c087e4c27943f9835f111
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
>>> uname -a
Darwin XXX 24.1.0 Darwin Kernel Version 24.1.0: Thu Oct 10 21:05:14 PDT 2024; root:xnu-11215.41.3~2/RELEASE_ARM64_T8103 arm64
```

## Additional context

I have double checked I am using the same Python requirements for each image.

[TIP]:  # ( Add any other context about the problem here. )

**Comment by mmiddha-wg** [comment]
I have been facing the same issue. Is this resolved now or it's in progress?

**Comment by kv5h** [comment]
> I have been facing the same issue. Is this resolved now or it's in progress?

@mmiddha-wg 
Hello, it’s not been fixed yet. As a workaround, you can specify previous version with Docker image hash. The hash can be found at GitHub Actions workflow history: https://github.com/newrelic/newrelic-lambda-layers/actions/runs/11381464884

**Comment by chaudharysaket** [comment]
Hi @mmiddha-wg 
We are working on this issue. 
Thank you @kv5h for providing workaround.

**Comment by TimPansino** [comment]
This should be fixed in the new agent version which will be published as a lambda layer within the next hour.
